article/urls.py
from django.urls import path
from article import views

app_name = 'article'
urlpatterns = [
        path('', views.article, name='article')
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
        path('', views.main, name='main'),
        path('about/', views.about, name='about')
]

practice_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')), 
    re_path('.*', views.main)
]

article/models.py
from django.db import models

# Create your models here.

article/views.py
from django.shortcuts import render

# Create your views here.

def article(request):
        '''
        Render the article page
        '''
        return render(request, 'article/article.html')

main/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
        '''
        Show 'Hello world!' in the main page
        '''
        context = {'like': 'Django great.'}
        return render(request, 'main/main.html', context)

def about(request):
        '''
        Render the about page
        '''
        return render(request, 'main/about.html')

article/templates/article/article.html
{% extends 'main/base.html' %}
{% block heading %}Welcome{% endblock %}
{% block content %}
{% endblock %}

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}About{% endblock %}
{% block content %}
<p>Welcome to my blog, you could browse any pages and leave the message.</p>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
<title>Blog</title>
<meta charset="utf-8">
</head>
<body>
{% include 'main/menu.html' %}
<h2>Blog -- {% block heading %}{% endblock %}</h2>
{% block content %}{% endblock %}
</body>
</html>

main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}Homepage{% endblock %}
{% block content %}
<p>{{ like }}</p>
{% endblock %}

main/templates/main/menu.html
<u1 id="menu">
        <li><a href="{% url 'main:main' %}">Homepage</a></li>
        <li><a href="{% url 'main:about' %}">About</a></li>
        <li><a href="{% url 'article:article' %}">Blog</a></li>
</u1>